variables:
  CURRENT_BRANCH_NAME: sk_splunk-app_v2 #"${INFRA_BRANCH}"

include:
  - file: .gitlab/ci/splunk-app/.gitlab-ci.yml
    ref: sk_splunk-app_v2 #"${INFRA_BRANCH}"
    project: "${CI_PROJECT_NAMESPACE}/infra"
